### ISSUE TITLE
no icon for paint select tool

### ISSUE THREAD

**Issue by Anikmoujegy** [Uzugijin/GIMP-IconThemes#1]
it's in playground.

**Comment by Uzugijin** [comment]
@Anikmoujegy Thanks for reporting! At some point I lost some icons for some reason. I restored paint select for now, but the other two playground tool are still not the correct colored icons. I'm aware of one more missing icon (it's the toggles) but it's going to be fixed when I clean up the whole blender pack, because the Symbolic pack also contains the default symbolic GIMP icons which is just bloat and I would like to merge the two packs into one but when i tried recently some icons got messed up. I have to study how to do it properly.
